"""empty message

Revision ID: 10b92c5f5314
Revises: 306b28206cd
Create Date: 2019-09-30 15:26:51.311867

"""

# revision identifiers, used by Alembic.
revision = '10b92c5f5314'
down_revision = '306b28206cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('pohlavi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_parent'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_parent_prijmeni', 'parent', ['prijmeni'], unique=False)
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], name='fk_child_parent_id_parent'),
    sa.PrimaryKeyConstraint('id', name='pk_child')
    )
    op.create_index('ix_child_jmeno', 'child', ['jmeno'], unique=False)
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index('ix_child_jmeno', table_name='child')
    op.drop_table('child')
    op.drop_index('ix_parent_prijmeni', table_name='parent')
    op.drop_table('parent')
    ### end Alembic commands ###
